#!/usr/bin/env python3
"""
Test Notification Sender - DRY通知のテスト

使い方:
    python scripts/send_test_notification.py

機能:
- DRY_RUN=true の場合: storage/notifications.jsonl に記録
- DRY_RUN=false の場合: 実際にEmail/Slackに送信
"""

import asyncio
from datetime import datetime
from core.notifier import Notifier, NotifierConfig


async def main():
    """メインエントリーポイント"""
    print("=" * 60)
    print("📧 Test Notification Sender")
    print("=" * 60)
    print()

    # Notifierインスタンス作成
    config = NotifierConfig()
    notifier = Notifier(config)

    print(f"DRY_RUN: {config.dry_run}")
    print(f"Channels: {config.channels or ['(none configured)']}")
    print()

    if config.dry_run:
        print("🔵 DRY_RUN MODE: Notifications will be saved to notifications.jsonl")
        print()
    else:
        print("🔴 REAL MODE: Notifications will be sent to configured channels")
        print()
        print("⚠️  WARNING: This will send actual notifications!")
        confirm = input("Continue? (yes/no): ")
        if confirm.lower() != "yes":
            print("Cancelled.")
            return

    # テスト通知を送信
    subject = f"Test Notification - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    body = """
This is a test notification from AI Multi-Agent Starter Kit.

Runner Status:
- Mode: DRY_RUN
- Jobs: heartbeat, cleanup, demo
- Status: Running

If you're seeing this, your notification system is working correctly!

---
Generated by scripts/send_test_notification.py
    """.strip()

    print("Sending test notification...")
    print()
    print(f"Subject: {subject}")
    print(f"Body: {body[:100]}...")
    print()

    result = await notifier.send(
        subject=subject,
        body=body,
        test=True,
        sender="send_test_notification.py"
    )

    print("=" * 60)
    print("📊 Result")
    print("=" * 60)
    print()

    if config.dry_run:
        print(f"✅ Notification recorded to: {config.notifications_file}")
        print()
        print("To view the notification:")
        print(f"  cat {config.notifications_file} | jq .")
        print()
        print("To send real notifications:")
        print("  1. Set DRY_RUN=false in .env")
        print("  2. Configure NOTIFY_CHANNELS (e.g., email,slack)")
        print("  3. Configure SMTP_* or SLACK_WEBHOOK_URL")
        print("  4. Run this script again")
    else:
        print("Results:")
        for channel, channel_result in result.get("results", {}).items():
            status = channel_result.get("status", "unknown")
            message = channel_result.get("message", "")

            if status == "success":
                print(f"  ✅ {channel}: {message}")
            else:
                print(f"  ❌ {channel}: {message}")

    print()
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())
